const fs=require('node:fs'),assert=require('node:assert/strict');
const {chromium}=require(process.env.OMNI_PLAYWRIGHT_PATH||'C:/Users/13758/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
let activeBrowser;
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 activeBrowser=browser;
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4173');
 await page.locator('#entries .entry').first().waitFor();
 await page.locator('#search').fill('喷火龙');
 assert.equal(await page.locator('#entries .entry').count(),5);
 await page.locator('#entries .entry').filter({hasText:'超级进化 X'}).click();
 assert((await page.locator('#detail h2').textContent()).includes('超级进化 X'));
 assert.equal(await page.getByRole('region',{name:'官方形态依据'}).locator('a').getAttribute('href'),'https://mega.pokemon.com/en-us/');
 await page.getByRole('button',{name:'登记形态',exact:true}).click();
 assert(await page.getByRole('button',{name:'✓ 登记形态',exact:true}).isDisabled());
 await page.reload();await page.locator('#entries .entry').first().waitFor();
 assert(await page.getByRole('button',{name:'✓ 登记形态',exact:true}).isDisabled());
 await page.locator('#search').fill('喷火龙');
 await page.locator('.portrait img').waitFor({timeout:7000}).catch(()=>{});
 await page.screenshot({path:'build/pokedex/desktop.png',fullPage:true});
 await page.locator('#category').selectOption('9');
 await page.locator('#search').fill('快龙');
 await page.locator('#entries .entry').first().click();
 assert(await page.getByRole('button',{name:'登记形态',exact:true}).isDisabled());
 assert((await page.locator('#detail').innerText()).includes('待核实'));
 await page.locator('#search').fill('不存在的精灵');
 assert((await page.locator('#entries').innerText()).includes('没有符合条件'));
 await page.getByRole('button',{name:'清除筛选'}).click();
 assert(await page.locator('#search').evaluate(el=>el===document.activeElement));
 await page.locator('#import').setInputFiles({name:'bad.odex',mimeType:'application/octet-stream',buffer:Buffer.from('invalid save')});
 await page.locator('#notice').filter({hasText:'未改变'}).waitFor();
 assert((await page.locator('#notice').innerText()).includes('未改变'));
 await page.locator('#search').fill('喷火龙');await page.locator('#entries .entry').filter({hasText:'超级进化 X'}).click();
 assert(await page.getByRole('button',{name:'✓ 登记形态',exact:true}).isDisabled());
 for(const [name,width,height] of [['tablet',820,1180],['mobile',390,844],['narrow',320,740]]){
  await page.setViewportSize({width,height});await page.screenshot({path:`build/pokedex/${name}.png`,fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${name}: horizontal overflow`);
 }
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.locator('#search').focus();await page.keyboard.press('Tab');
 assert(await page.locator('#category').evaluate(el=>el===document.activeElement));
 // Offline artwork is optional; actual data/core failures produce a retry path.
 for(const host of ['play.pokemonshowdown.com','raw.githubusercontent.com','zukan.pokemon.co.jp'])await page.route('https://'+host+'/**',r=>r.abort());
 await page.locator('#entries .entry').filter({hasText:'超级进化 Y'}).click();
 await page.locator('.image-note').filter({hasText:'参考图暂不可用'}).waitFor();
 const failed=await browser.newPage();await failed.route('**/catalog.json',r=>r.fulfill({status:503,body:'unavailable'}));
 await failed.goto('http://127.0.0.1:4173');await failed.getByRole('button',{name:'重新加载'}).waitFor();
 assert((await failed.locator('#notice').textContent()).includes('加载失败'));
 const removed=await browser.newPage();await removed.goto('http://127.0.0.1:4173/#dex%3Akakuna%3Abase%3Adynamax');
 await removed.locator('#notice').filter({hasText:'已移除'}).waitFor();
 assert.equal(await removed.locator('#detail h2').textContent(),'铁壳蛹');
 await removed.locator('#search').fill('铁壳蛹');assert.equal(await removed.locator('#entries .entry').count(),1);
 const hpPage=await browser.newPage({viewport:{width:1280,height:1000}});
 await hpPage.goto('http://127.0.0.1:4173/#dex%3Acharizard%3Abase%3Adynamax');
 await hpPage.locator('#hp-comparison').filter({hasText:'306'}).waitFor();
 assert((await hpPage.locator('#hp-comparison').innerText()).includes('153'));
 await hpPage.locator('#hp-dynamax').fill('0');assert((await hpPage.locator('#hp-comparison').innerText()).includes('229'));
 await hpPage.locator('#hp-dynamax').fill('11');assert((await hpPage.locator('#hp-comparison').innerText()).includes('整数'));
 await hpPage.locator('#hp-dynamax').fill('10');
 await hpPage.screenshot({path:'build/pokedex/hp-comparison-desktop.png',fullPage:true});
 await hpPage.setViewportSize({width:320,height:740});
 assert(await hpPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await hpPage.screenshot({path:'build/pokedex/hp-comparison-mobile.png',fullPage:true});
 await hpPage.goto('http://127.0.0.1:4173/#dex%3Aform%3Acharizardgmax');
 await hpPage.locator('#hp-comparison').filter({hasText:'306'}).waitFor();
 await hpPage.goto('http://127.0.0.1:4173/#dex%3Ashedinja%3Abase%3Adynamax');
 await hpPage.locator('#hp-comparison').filter({hasText:'固定 1 HP'}).waitFor();
 const catalog=require('../content/pokedex/catalog.json');
 const visit=async entry=>{await hpPage.goto('http://127.0.0.1:4173/#'+encodeURIComponent(entry.entry_id));await hpPage.locator('#detail h2').filter({hasText:entry.name_zh_hans}).waitFor();};
 await visit(catalog.entries.find(e=>e.entry_id==='dex:bulbasaur:base'));
 assert.equal(await hpPage.getByRole('region',{name:'官方形态依据'}).locator('a').getAttribute('href'),'https://zukan.pokemon.co.jp/detail/0001');
 await hpPage.locator('#announced summary').click();assert.equal(await hpPage.locator('#announced-list li').count(),5);
 assert((await hpPage.locator('#announced-list').textContent()).includes('叶眉鸟'));
 await visit(catalog.entries.find(e=>e.pokeapi?.identifier==='alcremie-rainbow-swirl-ribbon-sweet'&&e.category!=='dynamax'));
 assert((await hpPage.locator('#detail h2').textContent()).includes('蝴蝶结'));
 assert(await hpPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Alcremie variant controls overflow');
 await hpPage.screenshot({path:'build/pokedex/alcremie-mobile.png',fullPage:true});
 await visit(catalog.entries.find(e=>e.entry_id==='dex:pikachu:base'));
 await hpPage.locator('#art-shiny').check();await hpPage.locator('#art-female').check();
 const expected=catalog.entries.find(e=>e.entry_id==='dex:pikachu:base').art_reference.variants.front_shiny_female;
 await hpPage.locator('.portrait img').waitFor();assert.equal(await hpPage.locator('.portrait img').getAttribute('src'),expected);
 await visit(catalog.entries.find(e=>e.entry_id.endsWith(':rhyperior')&&e.author_evidence));
 assert((await hpPage.locator('#detail').textContent()).includes('670'));
 assert((await hpPage.locator('#detail').textContent()).includes('660'));
 assert(await hpPage.getByRole('button',{name:'登记形态',exact:true}).isDisabled());
 await hpPage.setViewportSize({width:1440,height:1050});await hpPage.screenshot({path:'build/pokedex/bond-author-desktop.png',fullPage:true});
 await visit(catalog.entries.find(e=>e.source_form_id==='garchompmegaz'));
 assert((await hpPage.locator('.portrait-row .facts').textContent()).includes('飘浮'));
 await visit(catalog.entries.find(e=>e.source_form_id==='ogerpontealtera'));
 await hpPage.locator('.portrait img').waitFor({timeout:15000});
 assert((await hpPage.locator('.art-controls').textContent()).includes('官方游戏截图'));
 await hpPage.screenshot({path:'build/pokedex/ogerpon-official.png',fullPage:true});
 await visit(catalog.entries.find(e=>e.entry_id==='dex:appearance:koraidon-swimming-build'));
 await hpPage.locator('.portrait img').waitFor({timeout:15000});
 assert((await hpPage.locator('.art-controls').textContent()).includes('官方游戏截图'));
 await visit(catalog.entries.find(e=>e.entry_id==='dex:appearance:miraidon-low-power-mode'));
 await hpPage.locator('.portrait img').waitFor({timeout:15000});
 assert((await hpPage.locator('.art-controls').textContent()).includes('社区图鉴参考图'));
 await visit(catalog.entries.find(e=>e.entry_id.endsWith(':rhyperior')&&e.author_evidence));
 await hpPage.locator('.portrait img').waitFor({timeout:15000});
 assert((await hpPage.locator('.art-controls').textContent()).includes('FYTYNo1'));
 await hpPage.setViewportSize({width:320,height:740});
 assert(await hpPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'credited sprite sheet overflow');
 for(const e of catalog.entries.filter(e=>e.art_reference.status==='ai_original_concept')){
  await visit(e);await hpPage.locator('.portrait img').waitFor();
  assert((await hpPage.locator('.concept-label').textContent()).includes('非官方／火箭队原图'));
  assert(await hpPage.getByRole('button',{name:'登记形态',exact:true}).isDisabled());
 }
 await hpPage.setViewportSize({width:1440,height:1050});
 await hpPage.screenshot({path:'build/pokedex/original-concept-desktop.png',fullPage:true});
 assert.deepEqual(errors,[]);await browser.close();
 console.log('PASS: desktop/tablet/mobile/320px rendered; Chinese search; independent Mega registration + reload; research protection; empty state; invalid import preserves records; keyboard focus; offline sprite fallback; dependency error/retry; no page errors');
})().catch(async e=>{console.error(e);if(activeBrowser)await activeBrowser.close();process.exitCode=1;});
