const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
 const data=JSON.parse(fs.readFileSync('content/pokedex/catalog.json','utf8'));
 const c=(await WebAssembly.instantiate(fs.readFileSync('build/pokedex/pokedex.wasm'),{})).instance.exports;
 assert.equal(c.dex_hp(78,50,31,0,0),153);
 assert.equal(c.dex_max_hp(153,10,0),306);
 assert.equal(c.dex_max_hp(153,0,0),229);
 assert.equal(c.dex_hp(78,100,31,252,0),360);
 assert.equal(c.dex_max_hp(1,10,1),1);
 assert.equal(c.dex_hp(78,50,256,0,0),0);
 for(let hp=1;hp<=714;hp++)for(let level=0;level<=10;level++)assert.equal(c.dex_max_hp(hp,level,0),Math.floor(hp*(30+level)/20));
 const put=bytes=>{const memory=new Uint8Array(c.memory.buffer,c.dex_input_ptr(),65536);memory.fill(0);memory.set(bytes);};
 const query=(text='',category=0,type=0,research=1)=>{put(new TextEncoder().encode(text));return c.dex_query(category,0,type,0,research,0,0);};
 assert.equal(c.dex_count(),data.entries.length);
 for(const id of ['weedle','kakuna','beedrill','sprigatito','zacian','zamazenta','eternatus'])assert(!data.entries.some(e=>e.category==='dynamax'&&e.source_form_id===id),`Unsupported Dynamax entry: ${id}`);
 assert(data.entries.some(e=>e.category==='dynamax'&&e.source_form_id==='charizard'));
 for(const e of data.entries.filter(e=>e.category==='dynamax'))assert(e.eligibility_evidence?.official_rule&&e.eligibility_evidence?.availability_reference);
 for(let i=0;i<data.entries.length;i++)assert.equal(c.dex_id(i)>>>0,data.entries[i].numeric_id);
 assert.equal(query(),data.entries.length);
 assert.equal(query('喷火龙'),data.entries.filter(e=>e.name_zh_hans.includes('喷火龙')).length);
 assert.equal(query('CHARIZARD'),query('charizard'));
 for(let cat=1;cat<=data.categories.length;cat++) assert.equal(query('',cat),data.entries.filter(e=>e.category_id===cat).length);
 for(let type=1;type<=data.types.length;type++)assert.equal(query('',0,type),data.entries.filter(e=>e.types.includes(data.types[type-1].id)).length);
 assert.equal(query('',0,0,0),data.entries.filter(e=>!e.research_only).length);
 const base=data.entries.findIndex(e=>e.entry_id==='dex:charizard:base'),mega=data.entries.findIndex(e=>e.source_form_id==='charizardmegax'),bond=data.entries.findIndex(e=>e.category==='rocket_bond_candidate');
 assert.equal(c.dex_record(mega,2),0);assert.equal(c.dex_flags(mega),3);assert.equal(c.dex_flags(base),0);
 assert.equal(c.dex_record(bond,2),3);assert.equal(c.dex_flags(bond),0);
 const n=c.dex_save(),save=new Uint8Array(c.memory.buffer,c.dex_input_ptr(),n).slice();
 const damaged=save.slice();damaged[12]^=1;put(damaged);assert.equal(c.dex_load(n),5);assert.equal(c.dex_flags(mega),3);
 put(save);assert.equal(c.dex_load(n),0);assert.equal(c.dex_flags(mega),3);
 console.log('PASS: full catalog C/Wasm ID parity; all category/type filters; Chinese and case-insensitive search; independent Mega progress; research protection; corrupt save atomicity');
})().catch(e=>{console.error(e);process.exitCode=1;});
