"""Compile original Omni cover art and a separate classic PRESS START sprite.

The high-resolution source is retained in assets/title. Hardware conversion only:
resize the full 3:2 illustration to 240x160, then quantize to GBA RGB555.
"""
import hashlib
import json
import struct
import urllib.request
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT/'build/pallet'
CACHE = ROOT/'.cache/title-source'
REV = 'c75f352304d529f6ba92d4f74b9cf8b5c3810788'
FILES = ['firered/background.pal', 'copyright_press_start.png', 'copyright_press_start.bin']
PROMPT_RECT = [72, 144, 96, 8]

def sha(b): return hashlib.sha256(b).hexdigest()

def layer(png, tilemap, palette):
    tiles = Image.open(CACHE/png)
    colors = [tuple(map(int, s.split()))+(255,) for s in (CACHE/palette).read_text().splitlines()[3:]]
    out = Image.new('RGBA', (256, 256))
    for n, (entry,) in enumerate(struct.iter_unpack('<H', (CACHE/tilemap).read_bytes())):
        tile = entry & 1023
        for y in range(8):
            for x in range(8):
                sx = tile % (tiles.width//8)*8 + (7-x if entry & 1024 else x)
                sy = tile // (tiles.width//8)*8 + (7-y if entry & 2048 else y)
                index = tiles.getpixel((sx, sy))
                # gbagfx main.c passes !image.hasPalette to ConvertToTiles4Bpp.
                if tiles.mode == 'L': index = 15-index//17
                if index: out.putpixel((n%32*8+x, n//32*8+y), colors[index])
    return out.crop((0, 0, 240, 160))

def main():
    records = []
    manifest_path = ROOT/'assets/source/title-screen.json'
    prior = json.loads(manifest_path.read_text('utf8')) if manifest_path.exists() else None
    for f in FILES:
        p = CACHE/f; p.parent.mkdir(parents=True, exist_ok=True)
        url = f'https://raw.githubusercontent.com/pret/pokefirered/{REV}/graphics/title_screen/{f}'
        if not p.exists(): p.write_bytes(urllib.request.urlopen(url, timeout=30).read())
        records.append({'path': f, 'url': url, 'sha256': sha(p.read_bytes())})
    if prior:
        for record in records:
            old = next((s for s in prior['sources'] if s['path'] == record['path']), None)
            assert old is None or old == record, 'Title prompt source hash changed'
    art = json.loads((ROOT/'assets/title/manifest.json').read_text('utf8'))
    source_path = ROOT/art['image']
    assert sha(source_path.read_bytes()) == art['sha256'], 'Cover source hash changed'
    with Image.open(source_path) as source:
        assert list(source.size) == art['dimensions'], 'Cover source dimensions changed'
        assert source.width*2 == source.height*3, 'Cover must be 3:2 without cropping'
        image = source.convert('RGBA').resize((240, 160), Image.Resampling.LANCZOS)
    prompt = layer('copyright_press_start.png', 'copyright_press_start.bin', 'firered/background.pal')
    OUT.mkdir(exist_ok=True, parents=True)
    prompt.save(OUT/'title-prompt-layout.png')
    # Preserve the source PRESS START pixels, but not its original release date.
    press = prompt.crop((40,128,136,136))
    blob = b''.join(struct.pack('<H', (r>>3) | ((g>>3)<<5) | ((b>>3)<<10)) for r,g,b,a in image.get_flattened_data())
    blob += b''.join(struct.pack('<H', 0x8000 if not a else (r>>3) | ((g>>3)<<5) | ((b>>3)<<10)) for r,g,b,a in press.get_flattened_data())
    assert len(blob) == 78336, 'Unexpected title ROM footprint'
    OUT.mkdir(exist_ok=True, parents=True)
    image.save(OUT/'title-art.png'); (OUT/'title.bin').write_bytes(blob)
    (OUT/'title.s').write_text(f'/* SHA256 {sha(blob)} */\n.section .rodata\n.balign 4\n.global omni_title_pixels\nomni_title_pixels:\n.incbin "build/pallet/title.bin"\n')
    x,y,w,h = PROMPT_RECT
    assert 0 <= x <= 240-w and 0 <= y <= 160-h
    (OUT/'title.h').write_text(f'''/* Generated by tools/build_title_assets.py. */
#ifndef OMNI_TITLE_H
#define OMNI_TITLE_H
#include <stdint.h>
extern const uint16_t omni_title_pixels[];
enum {{ OMNI_TITLE_PROMPT_X={x}, OMNI_TITLE_PROMPT_Y={y},
       OMNI_TITLE_PROMPT_W={w}, OMNI_TITLE_PROMPT_H={h} }};
#endif
''')
    manifest = {'schema_version': 2, 'sources': records,
                'art': {'manifest': 'assets/title/manifest.json', 'path': art['image'],
                        'sha256': art['sha256'], 'dimensions': art['dimensions'], 'tool': art['tool']},
                'adaptation': 'Original generated Omni illustration, full frame resized with Pillow LANCZOS and quantized to RGB555. Not an official game cover or literal world map. FireRed PRESS START pixels remain a separate blinking sprite, repositioned to the reserved bottom center.',
                'prompt_layout': PROMPT_RECT, 'prompt_source_crop': [40,128,96,8],
                'credits': {'illustration': art['credits'], 'prompt': 'Original Pokémon PRESS START graphics: Game Freak / Nintendo / Creatures; extraction reference: pret/pokefirered.'},
                'size': [240,160], 'bytes': len(blob), 'sha256': sha(blob)}
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2)+'\n', 'utf8')
    print(f'Title: {art["id"]}, {len(blob)} bytes, {len(records)} pinned prompt source files')

if __name__ == '__main__': main()
