"""Reproducible Omni anatomy policy. Reference measurements are not load ratings."""
import csv
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'research/catalog-sources'


def source_rows(name):
    manifest = json.loads((SOURCE / 'manifest.json').read_text('utf8'))
    record = next(r for r in manifest['files'] if r['file'] == name + '.csv')
    data = (SOURCE / record['file']).read_bytes()
    assert hashlib.sha256(data).hexdigest() == record['sha256'], record['file']
    return list(csv.DictReader(data.decode('utf8').splitlines()))


def main():
    measurements = {int(r['species_id']): r for r in source_rows('pokemon') if r['is_default'] == '1'}
    overrides = json.loads((ROOT / 'content/travel/anatomy-overrides.json').read_text('utf8'))
    rows = []
    for s in source_rows('pokemon_species'):
        number = int(s['id'])
        if number > 1025:
            continue
        m = measurements[number]
        height, weight, shape = int(m['height']), int(m['weight']), int(s['shape_id'])
        # Deliberately excludes upright/humanoid, amorphous, collective and head-only
        # bodies. Long serpents need explicit usable-back review; length is not width.
        support = int(shape in (3, 8, 9, 10, 14))
        body = int(height >= 10 and weight >= 300)
        safe = 1
        reason = 'size' if not body else 'support' if not support else 'morphology_rule'
        review = 'rule_classified_visual_review_pending'
        o = overrides.get(str(number), {})
        body = o.get('body', body)
        support = o.get('support', support)
        safe = o.get('safe_contact', safe)
        if o:
            reason, review = o['reason'], 'authored_anatomy_exception'
        eligible = bool(body and support and safe)
        rows.append(dict(species=number, identifier=s['identifier'], height_dm=height,
                         weight_hg=weight, shape_id=shape, body=body, support=support,
                         safe_contact=safe, clearance=o.get('clearance', 1),
                         eligible=eligible, locomotion='ground_bound', altitude=0,
                         grants_surf=False, reason=reason, review=review))
    assert [r['species'] for r in rows] == list(range(1, 1026))
    out = ROOT / 'content/travel/generated'
    out.mkdir(parents=True, exist_ok=True)
    (out / 'profiles.json').write_text(json.dumps(dict(schema=1,
        scope='1025 default species; alternate forms require separate anatomy review',
        rules='Omni design: support-shaped body >=1.0m and >=30kg; explicit anatomy/safety exceptions. Not official carrying capacity.',
        profiles=rows), ensure_ascii=False, indent=2) + '\n', 'utf8')
    lines = ['/* Generated by tools/build_travel_profiles.py. Do not hand edit. */']
    for r in rows:
        # Physical land presentation is universal. Water access is separately authorized.
        lines.append('{%d,%d,%d,%d,OMNI_LAND,%d},' % tuple(r[k] for k in
            ('species', 'body', 'support', 'safe_contact', 'clearance')))
    (out / 'profiles.inc').write_text('\n'.join(lines) + '\n', 'utf8')
    catalog = json.loads((ROOT/'content/pokedex/catalog.json').read_text('utf8'))['entries']
    base = {e['national_number']: e for e in catalog if e['category'] == 'base'}
    lines = ['/* Reference stats for travel sandbox; no authored moveset or acquisition. */']
    for r in rows:
        if not r['eligible']:
            continue
        e = base[r['species']]
        stats = ','.join(str(e['stats'][k]) for k in ('hp','atk','def','spa','spd','spe'))
        lines.append('{%d,{%s},{0},{0},%s,"—"},' % (r['species'], stats, json.dumps(e['name_zh_hans'], ensure_ascii=False)))
    (out / 'partners.inc').write_text('\n'.join(lines)+'\n', 'utf8')
    print(f'PASS: {len(rows)} species classified, {sum(r["eligible"] for r in rows)} riding candidates; no altitude or implicit Surf')


if __name__ == '__main__':
    main()
